<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; Importância das frações de N e P para predição dos estoques totais (PLSR) – Modelagem Fuzzy-PLS da Dinâmica de Fósforo e Nitrogênio em Usos do Solo no Sul do Tocantins</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/06-conclusion.html" rel="next">
<link href="../chapters/03-methodology.html" rel="prev">
<link href="../cover.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-707d8167ce6003fca903bfe2be84ab7f.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-223b1c1c17562845a8a6567057edd50a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-bbbab825ba9eab20df0aa2cb29561c94.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-223b1c1c17562845a8a6567057edd50a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../custom.css">
</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/04-results.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Resultados e Discussão</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Modelagem Fuzzy-PLS da Dinâmica de Fósforo e Nitrogênio em Usos do Solo no Sul do Tocantins</a> 
        <div class="sidebar-tools-main tools-wide">
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="../Modelagem-Fuzzy-PLS-da-Dinâmica-de-Fósforo-e-Nitrogênio-em-Usos-do-Solo-no-Sul-do-Tocantins.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="../Modelagem-Fuzzy-PLS-da-Dinâmica-de-Fósforo-e-Nitrogênio-em-Usos-do-Solo-no-Sul-do-Tocantins.docx">
              <i class="bi bi-file-word pe-1"></i>
            Download Docx
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Resumo</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introdução</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-methodology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Metodologia</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-results.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Resultados e Discussão</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-conclusion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Conclusão</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referências</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#resultados-e-discussão" id="toc-resultados-e-discussão" class="nav-link active" data-scroll-target="#resultados-e-discussão"><span class="header-section-number">4</span> Resultados e Discussão</a>
  <ul class="collapse">
  <li><a href="#predição-do-nitrogênio-total" id="toc-predição-do-nitrogênio-total" class="nav-link" data-scroll-target="#predição-do-nitrogênio-total"><span class="header-section-number">4.0.1</span> Predição do Nitrogênio Total</a></li>
  <li><a href="#predição-do-fósforo-total" id="toc-predição-do-fósforo-total" class="nav-link" data-scroll-target="#predição-do-fósforo-total"><span class="header-section-number">4.0.2</span> 3.1.2 Predição do Fósforo Total</a></li>
  <li><a href="#relações-estruturais-entre-frações-lábeis-húmicas-e-estoques-totais-pls-sem" id="toc-relações-estruturais-entre-frações-lábeis-húmicas-e-estoques-totais-pls-sem" class="nav-link" data-scroll-target="#relações-estruturais-entre-frações-lábeis-húmicas-e-estoques-totais-pls-sem">Relações estruturais entre frações lábeis, húmicas e estoques totais (PLS-SEM)</a>
  <ul class="collapse">
  <li><a href="#resultados-do-modelo-estrutural-global" id="toc-resultados-do-modelo-estrutural-global" class="nav-link" data-scroll-target="#resultados-do-modelo-estrutural-global"><span class="header-section-number">4.0.3</span> 3.2.1 Resultados do modelo estrutural global</a></li>
  <li><a href="#resultados-da-análise-multigrupo-por-uso-da-terra-pls-mga" id="toc-resultados-da-análise-multigrupo-por-uso-da-terra-pls-mga" class="nav-link" data-scroll-target="#resultados-da-análise-multigrupo-por-uso-da-terra-pls-mga"><span class="header-section-number">4.0.4</span> 3.2.3 Resultados da análise multigrupo por uso da terra (PLS-MGA)</a></li>
  </ul></li>
  <li><a href="#integração-fuzzy-da-funcionalidade-edáfica-índice-de-sustentabilidade-fsnsi" id="toc-integração-fuzzy-da-funcionalidade-edáfica-índice-de-sustentabilidade-fsnsi" class="nav-link" data-scroll-target="#integração-fuzzy-da-funcionalidade-edáfica-índice-de-sustentabilidade-fsnsi">Integração fuzzy da funcionalidade edáfica: Índice de Sustentabilidade (FSNSI)</a>
  <ul class="collapse">
  <li><a href="#sistema-de-inferência-fuzzy-e-funções-de-pertinência" id="toc-sistema-de-inferência-fuzzy-e-funções-de-pertinência" class="nav-link" data-scroll-target="#sistema-de-inferência-fuzzy-e-funções-de-pertinência"><span class="header-section-number">4.0.5</span> 3.3.1 Sistema de inferência fuzzy e funções de pertinência</a></li>
  <li><a href="#estratificação-vertical-do-fsnsi" id="toc-estratificação-vertical-do-fsnsi" class="nav-link" data-scroll-target="#estratificação-vertical-do-fsnsi"><span class="header-section-number">4.0.6</span> 3.3.3 Estratificação vertical do FSNSI</a></li>
  <li><a href="#correlações-entre-variáveis-de-entrada-e-fsnsi" id="toc-correlações-entre-variáveis-de-entrada-e-fsnsi" class="nav-link" data-scroll-target="#correlações-entre-variáveis-de-entrada-e-fsnsi"><span class="header-section-number">4.0.7</span> 3.3.4 Correlações entre variáveis de entrada e FSNSI</a></li>
  </ul></li>
  <li><a href="#articulação-entre-plsr-pls-sem-e-inferência-fuzzy" id="toc-articulação-entre-plsr-pls-sem-e-inferência-fuzzy" class="nav-link" data-scroll-target="#articulação-entre-plsr-pls-sem-e-inferência-fuzzy">Articulação entre PLSR, PLS-SEM e inferência fuzzy</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"><h1 class="title display-7"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Importância das frações de N e P para predição dos estoques totais (PLSR)</span></h1></header>


<header id="title-block-header">


</header>


<section id="resultados-e-discussão" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Resultados e Discussão</h1>
<p>A análise de regressão por mínimos quadrados parciais (PLSR) revelou que as frações de nitrogênio e fósforo apresentam contribuições diferenciadas para a predição dos estoques totais desses nutrientes no solo. A análise dos escores de importância das variáveis (VIP) identificou as frações mais relevantes para explicar a variabilidade de NT e PT nos sistemas estudados.</p>
<section id="predição-do-nitrogênio-total" class="level3" data-number="4.0.1">
<h3 data-number="4.0.1" class="anchored" data-anchor-id="predição-do-nitrogênio-total"><span class="header-section-number">4.0.1</span> Predição do Nitrogênio Total</h3>
<p>A análise PLSR para o nitrogênio total (NT) foi realizada utilizando as frações de N como variáveis preditoras, permitindo identificar as contribuições relativas de cada compartimento funcional. Os resultados são apresentados na Figura 4, que mostra o biplot com os scores das amostras por uso da terra e os loadings das variáveis preditoras, evidenciando a estrutura de covariância entre as frações e os estoques totais. Os resultados demonstram que as frações húmicas NTHum e NTAH são as preditoras mais importantes (VIP &gt; 1.0), indicando sua dominância na explicação dos estoques totais de N. As frações lábeis NLabil e NMOL também contribuem significativamente (VIP 0.8-1.0), enquanto NTAF apresenta relevância moderada (Figura 4). Esse padrão reflete a importância das frações húmicas como reservatórios estáveis de N em solos tropicais, corroborando estudos que destacam seu papel na sustentabilidade nutricional <span class="citation" data-cites="paul2016">(<a href="../references.html#ref-paul2016" role="doc-biblioref">Paul, 2016</a>)</span>.</p>
<p>A Tabela 2 sintetiza os escores de importância na projeção (VIP) obtidos a partir do modelo PLSR. O modelo foi estimado com duas componentes latentes, que explicaram mais de 80% da variância acumulada entre preditores e resposta, com validação cruzada leave-one-out para checagem da robustez preditiva. As frações húmicas especialmente NTHum (VIP ˜ 1.2–1.5) e NTAH (VIP ˜ 1.1–1.3), apresentaram os maiores valores de VIP, caracterizando-se como preditores críticos para a variabilidade do nitrogênio total (NT). As frações lábeis (NLabil e NMOL) exibiram VIP próximos a 0.8–1.0, indicando contribuição relevante porém secundária, enquanto NTAF mostrou relevância moderada (VIP &lt; 0.8).</p>
<p>Esses resultados são congruentes com a interpretação funcional em que as frações húmicas, por possuírem maior massa molar, maior associação organo-mineral e resistência à mineralização, atuam como reservatórios de longo prazo que determinam os estoques totais de N; já as frações lábeis refletem pools de rápida renovação e resposta a entradas recentes de matéria orgânica e manejo. No biplot (Figura 4) observa-se segregação espacial das amostras por uso da terra, com agrupamentos associados a maiores loadings húmicos (por exemplo, Eucalipto e Cerrado) e outros mais voltados ao eixo de frações lábeis (Agricultura e Pastagem), o que corrobora a hipótese de que a qualidade da serapilheira e o manejo estrutural modulam a composição funcional do pool de N.</p>
<p>Do ponto de vista gerencial e ecológico, a predominância das frações húmicas na predição do NT indica que práticas voltadas ao aumento da estabilidade da MOS (redução do revolvimento, incremento de inputs lignificados, manutenção de cobertura morta) tendem a promover retenção de N em formas de maior persistência, fortalecendo a capacidade de armazenamento e a resiliência do sistema. Em contrapartida, sistemas com maior proporção de frações lábeis apresentam maior disponibilidade imediata de N, porém menor capacidade de retenção a longo prazo, implicando necessidade de intervenções de manejo contínuo para manutenção da fertilidade.</p>
</section>
<section id="predição-do-fósforo-total" class="level3" data-number="4.0.2">
<h3 data-number="4.0.2" class="anchored" data-anchor-id="predição-do-fósforo-total"><span class="header-section-number">4.0.2</span> 3.1.2 Predição do Fósforo Total</h3>
<p>De forma similar ao observado para o nitrogênio, os teores de P total (PT) e suas frações húmicas (PTHum, PTAH, PLabil) apresentaram elevada correlação estrutural no modelo PLSR (Figura 5). Esse comportamento está alinhado ao conceito de co-acúmulo e co-estabilização de nutrientes na MOS, segundo o qual P e N se associam a complexos organo-minerais ou são adsorvidos simultaneamente a colóides orgânicos e minerais, favorecendo a persistência dos estoques totais <span class="citation" data-cites="helfenstein2020 tivet2013">(<a href="../references.html#ref-tivet2013" role="doc-biblioref">Tivet et al., 2013</a>, <a href="../references.html#ref-helfenstein2020" role="doc-biblioref">Helfenstein et al., 2020</a>)</span>. A aplicação de técnicas multivariadas como PLSR em estudos de ciência do solo tem se mostrado particularmente adequada para lidar com conjuntos de dados caracterizados por multicolinearidade entre variáveis, conforme demonstrado por <span class="citation" data-cites="sekaran2020">Sekaran et al. (<a href="../references.html#ref-sekaran2020" role="doc-biblioref">2020</a>)</span> em análises de atividades bioquímicas e estrutura de comunidades microbianas do solo.</p>
<p>A correlação entre PLabil/PMOL e as frações húmicas de P sugere sinergia entre disponibilidade de nutrientes e fracionamento da matéria orgânica, indicando processos dinâmicos de transformação e estabilização do fósforo no solo. Os mecanismos de co-estabilização envolvem (i) adsorção específica de ortofosfato (H2PO4?) em superfícies de ácidos húmicos via pontes de hidrogênio e complexação com grupos funcionais carboxílicos e fenólicos, (ii) formação de complexos ternários envolvendo P orgânico, cátions polivalentes (Ca²?, Fe³?, Al³?) e substâncias húmicas, que reduzem a solubilidade e a mobilidade do fósforo no perfil, e (iii) oclusão física de P lábil em microagregados estabilizados por humina e material recalcitrante, protegendo-o contra mineralização rápida. Esses processos são particularmente relevantes em Latossolos altamente intemperizados, onde a mineralogia dominada por caulinita, gibbsita e óxidos de Fe/Al apresenta elevada capacidade de fixação de P, e a MOS atua como moduladora dessa fixação através de competição por sítios de adsorção.</p>
<p><img src="../figures/biplot_plsr_pt.png" id="fig:5" class="img-fluid" style="width:90.0%" alt="Figura 5. Biplot PLSR para PT, mostrando scores das amostras por uso da terra e loadings das variáveis preditoras de fósforo."> Nota: Padrão visual similar ao do NT, refletindo a associação estrutural entre N e P no solo.</p>
<p>Os escores VIP para as frações de P revelaram padrão similar ao do nitrogênio, com PTHum e PTAH como preditores dominantes (Tabela 5). Esse paralelismo estrutural entre N e P reforça que os processos de humificação progressiva—onde compostos lábeis são gradativamente convertidos em frações húmicas intermediárias (ácidos fúlvicos ? ácidos húmicos) e finalmente em humina recalcitrante—operam de forma sincronizada para ambos os nutrientes. A predominância de PTHum como preditor-chave reflete o fato de que, em solos tropicais sob vegetação estabelecida, a maior parte do P orgânico encontra-se imobilizada em formas estáveis de longa persistência (décadas a séculos), contrastando com sistemas agrícolas onde o revolvimento frequente acelera a mineralização e favorece o acúmulo relativo de frações lábeis. A correlação significativa entre VIP(PTHum) e VIP(NTHum) (r &gt; 0.85) evidencia que os mesmos fatores edafoclimáticos—temperatura, umidade, atividade microbiana, textura do solo—regulam simultaneamente o fracionamento de P e N, sugerindo que estratégias de manejo direcionadas à conservação de frações húmicas beneficiam ambos os nutrientes de forma integrada.</p>
<table class="caption-top table">
<caption>Tabela 5 - Escores VIP das variáveis preditoras de PT (Variável Importance in Projection). VIP &gt; 1.0 indica variáveis críticas para a predição do PT.</caption>
<thead>
<tr class="header">
<th>Variável</th>
<th>VIP</th>
<th>Relevância</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>PTHum</td>
<td>&gt; 1.0</td>
<td>Muito importante</td>
</tr>
<tr class="even">
<td>PTAH</td>
<td>&gt; 1.0</td>
<td>Muito importante</td>
</tr>
<tr class="odd">
<td>PLabil</td>
<td>0.8-1.0</td>
<td>Importante</td>
</tr>
<tr class="even">
<td>PMOL</td>
<td>0.8-1.0</td>
<td>Importante</td>
</tr>
<tr class="odd">
<td>PTAF</td>
<td>&lt; 0.8</td>
<td>Moderada</td>
</tr>
</tbody>
</table>
<p>Esses achados reforçam que a predição de NT e PT em sistemas edáficos tropicais deve considerar não apenas frações diretamente associadas a cada elemento, mas também a natureza multinutriente da MOS e sua co-regulação pelas vias biogeoquímicas de decomposição, complexação e proteção físico-química. A elevada capacidade preditiva do modelo PLSR (variância explicada &gt; 80% com duas componentes latentes) demonstra que o fracionamento químico capta efetivamente os processos funcionais que governam a disponibilidade de nutrientes, fornecendo base sólida para desenvolvimento de indicadores de qualidade do solo e monitoramento de trajetórias de degradação ou recuperação em diferentes sistemas de uso da terra.</p>
</section>
<section id="relações-estruturais-entre-frações-lábeis-húmicas-e-estoques-totais-pls-sem" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="relações-estruturais-entre-frações-lábeis-húmicas-e-estoques-totais-pls-sem">Relações estruturais entre frações lábeis, húmicas e estoques totais (PLS-SEM)</h2>
<section id="resultados-do-modelo-estrutural-global" class="level3" data-number="4.0.3">
<h3 data-number="4.0.3" class="anchored" data-anchor-id="resultados-do-modelo-estrutural-global"><span class="header-section-number">4.0.3</span> 3.2.1 Resultados do modelo estrutural global</h3>
<p>O modelo estrutural foi configurado como um modelo de componentes hierárquicos (hierarchical component model, HCM) em dois níveis, combinando construtos de primeira ordem que representam as frações funcionais de nitrogênio e fósforo e construtos de segunda ordem que sintetizam os estoques totais. Essa abordagem segue as recomendações de <span class="citation" data-cites="hair2021">Hair et al. (<a href="../references.html#ref-hair2021" role="doc-biblioref">2021</a>)</span> para modelagem de estruturas reflexivas com indicadores repetidos, assegurando que a variância compartilhada entre as dimensões funcionais seja propagada para os construtos superiores. No primeiro nível, N_lábil e P_lábil foram medidos pelos pares NLabil/NMOL e PLabil/PMOL, enquanto N_húmico e P_húmico agregaram NTAF, NTAH, NTHum e PTAF, PTAH, PTHum, respectivamente. A etapa de mensuração revelou cargas fatoriais elevadas (? = 0.981 a 0.990) para todos os indicadores, confirmando que as variáveis manifestas capturam de forma robusta a variabilidade intrínseca de cada fração funcional (Figura 6).</p>
<p><img src="../figures/analise_caminhos_pls.png" id="fig:6" class="img-fluid" style="width:95.0%" alt="Figura 6. Análise de caminhos do modelo PLS-SEM evidenciando as relações estruturais entre variáveis latentes (frações de nitrogênio e fósforo) e indicadores observáveis."> Nota: As setas indicam as trajetórias de influência causal, com largura proporcional à magnitude dos coeficientes de caminho. O modelo revela que as frações húmicas de N e P apresentam maior poder preditivo dos estoques totais comparativamente às frações lábeis, com coeficientes de caminho variando entre ambientes de estudo, demonstrando heterogeneidade funcional induzida pelo manejo.</p>
<p>A consistência interna elevada (a &gt; 0.97) e a variância média extraída acima de 0.95 (Tabela 4) indicam confiabilidade convergente excelente para todos os construtos, superando com folga os limiares recomendados para estudos com estruturas reflexivas <span class="citation" data-cites="hair2021">(<a href="../references.html#ref-hair2021" role="doc-biblioref">Hair et al., 2021</a>)</span>. A inspeção da matriz de cargas cruzadas e da razão HTMT confirmou ausência de problemas de validade discriminante, demonstrando que as frações lábeis e húmicas retêm especificidades conceituais mesmo quando agregadas em construtos de segunda ordem. Dessa forma, a etapa de mensuração oferece base robusta para interpretar os resultados estruturais, minimizando o risco de vieses associados a colinearidade excessiva entre indicadores.</p>
<p>Na etapa estrutural, o modelo global apresentou coeficiente de determinação de 0.959 tanto para N_total quanto para P_total, explicando praticamente toda a variabilidade observada dos estoques em condições de Cerrado (Tabela 4). Esse nível de ajuste é raro em estudos edáficos e indica que o fracionamento funcional resume a maior parte dos processos que modulam o acúmulo de N e P. Os coeficientes de caminho oriundos das frações húmicas (ß = 1.286 para N_húmico ? N_total e P_húmico ? P_total) foram positivos, elevados e estatisticamente diferentes de zero nas reamostragens bootstrap, evidenciando que acréscimos marginais nesses compartimentos resultam em aumentos proporcionais superiores nos estoques totais. Esse comportamento é coerente com evidências de campo que apontam as frações húmicas como reservatórios dominantes de nutrientes em Latossolos sob silvicultura e pastagens de longa duração <span class="citation" data-cites="pegoraro2011 ferreira2021">(<a href="../references.html#ref-pegoraro2011" role="doc-biblioref">Pegoraro et al., 2011</a>, <a href="../references.html#ref-ferreira2021" role="doc-biblioref">Ferreira et al., 2021</a>)</span>.</p>
<table class="caption-top table">
<caption>Tabela 4 - Métricas de qualidade do modelo PLS-SEM global. Nota: Os valores indicam adequação do modelo aos dados empíricos conforme critérios de referência da metodologia.</caption>
<thead>
<tr class="header">
<th>Métrica</th>
<th>Valor Observado</th>
<th>Interpretação</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R² (N_total)</td>
<td>0.959 (Cerrado)</td>
<td>Explicação de 95.9% da variância</td>
</tr>
<tr class="even">
<td>R² (P_total)</td>
<td>0.959 (Cerrado)</td>
<td>Explicação de 95.9% da variância</td>
</tr>
<tr class="odd">
<td>SRMR</td>
<td>&lt; 0.06</td>
<td>Modelo bem ajustado aos dados</td>
</tr>
<tr class="even">
<td>Confiabilidade (a)</td>
<td>&gt; 0.97</td>
<td>Consistência interna &gt; 0.97</td>
</tr>
<tr class="odd">
<td>Comunalidade (AVE)</td>
<td>&gt; 0.95</td>
<td>Variância média bem explicada</td>
</tr>
</tbody>
</table>
<p>Os coeficientes negativos associados às frações lábeis (ß = -0.313 para N_lábil ? N_total e P_lábil ? P_total) refletem o mecanismo de particionamento entre pools de rápida renovação e reservas estáveis. À medida que o sistema acumula compostos recalcitrantes, parte das formas lábeis é incorporada à matriz húmica, produzindo efeito inverso nos modelos estruturais. Esse resultado tem respaldo em cronossequências que documentam a transferência progressiva de N e P lábeis para frações humificadas durante a maturação de sistemas florestais e agrícolas <span class="citation" data-cites="marinhojunior2021 araujofilho2024">(<a href="../references.html#ref-marinhojunior2021" role="doc-biblioref">Marinho Junior et al., 2021</a>, <a href="../references.html#ref-araujofilho2024" role="doc-biblioref">Araújo Filho et al., 2024</a>)</span>. Não se trata, portanto, de antagonismo biogeoquímico, mas de evidência de que o modelo capturou a dinâmica de humificação incremental do sistema.</p>
<p>A simetria dos coeficientes entre N e P reforça a hipótese de acoplamento biogeoquímico dos dois macronutrientes, governado por processos comuns de humificação, complexação organo-mineral e proteção estrutural da matéria orgânica. Esse padrão corrobora observações em agroflorestas de café sombreado no Nordeste, onde o incremento do carbono orgânico total está associado simultaneamente a aumentos nas frações húmicas de N e P e à melhoria da estrutura física do solo <span class="citation" data-cites="crespo2024">(<a href="../references.html#ref-crespo2024" role="doc-biblioref">Crespo et al., 2024</a>)</span>. Os resultados do PLS-SEM confirmam que a estabilização conjunta de N e P é um atributo-chave de sistemas manejados com alta entrada de resíduos lignificados, elemento central para compreender a funcionalidade edáfica nos usos da terra avaliados.</p>
<p>A modelagem por equações estruturais baseada em mínimos quadrados parciais (PLS-SEM) permitiu quantificar as contribuições relativas das frações lábeis e húmicas de N e P para os estoques totais desses nutrientes. O resultado mais significativo foi o alcance de R² = 0.959 para ambos N_total e P_total no ambiente Cerrado, indicando que o modelo explica 95.9% da variância observada. Esse coeficiente de determinação representa performance excepcional em modelagem de sistemas edáficos complexos, especialmente considerando a heterogeneidade inerente aos ecossistemas de solo tropical, caracterizados por variabilidade espacial elevada e múltiplos mecanismos de transformação de nutrientes. A replicação desse desempenho entre N e P (R² = 0.959 para ambos) evidencia que os mesmos compartimentos funcionais (frações húmicas e lábeis) operem como determinantes estruturais para ambos os macronutrientes, sugerindo acoplamento geoquímico estreito entre as dinâmicas de N e P nessa matriz de solo.</p>
<p>O diagrama do modelo (Figura 6) representa graficamente essa arquitetura, onde retângulos indicam variáveis manifestas (indicadores observáveis), hexágonos representam construtos latentes (variáveis não observadas diretamente) e setas mostram as relações causais hipotéticas. As cargas fatoriais elevadas (? = 0.981-0.990 para todos os indicadores) confirmam a qualidade excepcional da medição das variáveis latentes, validando a escolha dos indicadores para representação das frações de nutrientes.</p>
<p>A relação positiva dominante das frações húmicas (ß = 1.286) corrobora a hipótese de que essas frações constituem o principal reservatório de longo prazo desses nutrientes, representando aproximadamente 56% a mais da contribuição unitária para os estoques totais comparativamente aos terços finais do modelo. A magnitude de ß = 1.286 indica que incrementos de uma unidade na fração húmica geram aumento de 1.286 unidades no estoque total, estabelecendo essas frações como preditoras dominantes da disponibilidade de nutrientes no sistema. Essa dominância das frações húmicas é consistente com observações de <span class="citation" data-cites="pegoraro2011">Pegoraro et al. (<a href="../references.html#ref-pegoraro2011" role="doc-biblioref">2011</a>)</span>, que demonstraram que substâncias húmicas (ácidos fúlvicos, húmicos e huminas) representam os principais compartimentos de C e N em solos sob diferentes usos da terra, e com <span class="citation" data-cites="ferreira2021">Ferreira et al. (<a href="../references.html#ref-ferreira2021" role="doc-biblioref">2021</a>)</span>, que evidenciaram que a matéria orgânica associada aos minerais (MAOM) constitui o reservatório mais estável de nutrientes em solos tropicais brasileiros.</p>
<p>Estudos em sistemas agroflorestais sombreados confirmam esse padrão, demonstrando que a presença de árvores nativas modula significativamente os processos biogeoquímicos do solo. <span class="citation" data-cites="crespo2024">Crespo et al. (<a href="../references.html#ref-crespo2024" role="doc-biblioref">2024</a>)</span> evidenciaram em sistemas de café sombreado que o carbono orgânico total (COT) atua como integrador central entre porosidade, acidez e disponibilidade de nutrientes, sendo que áreas com maior cobertura arbórea apresentaram COT superior a 2.5% e microporosidade de ~30%, refletindo o acúmulo coluvial e a proteção contra a mineralização acelerada. A análise de componentes principais nesses sistemas explicou 60.2% da variação total, com PC1 (estrutura física e fertilidade, 38.5%) e PC2 (qualidade da matéria orgânica, 21.7%), corroborando a importância das frações húmicas como determinantes estruturais da funcionalidade edáfica. Esses resultados reforçam que a integração entre diversidade arbórea e processos pedogenéticos favorece a estabilização de nutrientes nas frações húmicas, processo particularmente relevante em Latossolos altamente intemperizados onde a baixa capacidade de troca catiônica amplia a dependência da matéria orgânica para retenção de N e P.</p>
<p>A relação negativa das frações lábeis (ß = -0.313), embora aparentemente contraditória à primeira vista, reflete um mecanismo biogeoquímico fundamental em solos tropicais: a colinearidade estrutural representada no modelo constitui transformação matemática da interação dinâmica entre pools. Especificamente, quando a fração húmica aumenta, a fração lábil diminui relativamente, pois o modelo captura o fenômeno de humificação progressiva onde compartimentos lábeis são continuamente convertidos em frações húmicas recalcitrantes <span class="citation" data-cites="marinhojunior2021">(<a href="../references.html#ref-marinhojunior2021" role="doc-biblioref">Marinho Junior et al., 2021</a>)</span>. Essa dinâmica não indica relação causal negativa entre os compartimentos, mas sim descreve a natureza do particionamento de nutrientes: em solos com elevada decomposição microbiana (como o Cerrado), a conversão N_lábil ? N_húmico ? N_recalcitrante ocorre sequencialmente, resultando em compensação de sinais nos coeficientes de regressão múltipla. O padrão ß(húmico) = +1.286 e ß(lábil) = -0.313 mantém proporcionalidade esperada, onde N_total = 1.286×N_húmico - 0.313×N_lábil apresenta ajuste estatístico que evita multicolinearidade excessiva.</p>
<p>Essa interpretação encontra suporte direto na observação dos dados: se as frações húmicas fossem verdadeiramente prejudiciais (como indicaria um ß negativo), sistemas com elevada humificação não apresentariam acúmulo consistente de nutrientes. Inversamente, o padrão observado confirma que as frações húmicas exercem efeito funcional positivo, validando a interpretação de que os coeficientes negativos no PLS-SEM refletem estrutura matemática de compensação em vez de antagonismo biogeoquímico.</p>
</section>
<section id="resultados-da-análise-multigrupo-por-uso-da-terra-pls-mga" class="level3" data-number="4.0.4">
<h3 data-number="4.0.4" class="anchored" data-anchor-id="resultados-da-análise-multigrupo-por-uso-da-terra-pls-mga"><span class="header-section-number">4.0.4</span> 3.2.3 Resultados da análise multigrupo por uso da terra (PLS-MGA)</h3>
<p>A Figura 7 evidencia que a análise multigrupo (PLS-MGA) expôs heterogeneidade marcante na arquitetura estrutural entre os usos da terra, com coeficientes de caminho modulados pelo manejo e pela biomassa depositada. O Cerrado nativo sustenta o maior efeito húmico entre os sistemas naturais (ß = 1.286), configurando a referência biogeoquímica de humificação equilibrada na qual acúmulo e mineralização operam em dinâmica quasi-estacionária. Esse patamar delineia a linha de base usada para interpretar os desvios observados nos demais ambientes. A agricultura convencional desloca-se dessa referência ao apresentar ß(húmico) = 1.180, 8.2% inferior ao Cerrado. A redução indica reconfiguração do particionamento entre pools: a menor contribuição húmica é acompanhada por fração lábil menos negativa (-0.237 contra -0.313 no Cerrado), sinalizando que o revolvimento mecânico e a entrada recorrente de fertilizantes minerais mantêm proporção elevada de compostos rapidamente disponíveis. Em sistemas agrícolas tropicais, tais práticas aceleram a transferência de N e P das reservas estáveis para formas solúveis, tornando indispensável a adubação de manutenção para evitar quedas abruptas nos estoques <span class="citation" data-cites="santos2024">(<a href="../references.html#ref-santos2024" role="doc-biblioref">Santos et al., 2024</a>)</span>.</p>
<div id="fig:7" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="../figures/comparacao_coeficientes.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Figura 7. Comparação dos coeficientes de caminho entre os diferentes usos da terra. Barras agrupadas mostram a magnitude dos efeitos (N_húmico ? N_total e P_húmico ? P_total) para cada ambiente. Cores distintas representam os cinco sistemas de uso avaliados.</figcaption>
</figure>
</div>
<p>Os sistemas silviculturais ocupam faixa intermediária (Tabela 5) em que, o Mogno-africano (ß = 1.271) conserva estrutura similar ao Cerrado, coerente com regime de manejo menos intensivo e serapilheira de decomposição moderada. O Eucalipto (ß = 1.275) supera ligeiramente o Mogno, refletindo acúmulo expressivo de resíduos lignificados que favorecem a incorporação de N e P nas frações húmicas, fenômeno já documentado para plantações maduras da espécie <span class="citation" data-cites="pegoraro2011 ferreira2021">(<a href="../references.html#ref-pegoraro2011" role="doc-biblioref">Pegoraro et al., 2011</a>, <a href="../references.html#ref-ferreira2021" role="doc-biblioref">Ferreira et al., 2021</a>)</span>. A Teca, contudo, apresenta o coeficiente máximo (ß = 1.372), indicando humificação intensificada. Embora à primeira vista pareça indicativo de maior estabilidade, o valor elevado ocorre em conjunto com estoques totais mais baixos e com densidade aparente elevada, sugerindo que a serapilheira recalcitrante da Teca retarda a ciclagem e concentra nutrientes em compartimentos pouco acessíveis. A progressão Cerrado ? Mogno ? Eucalipto ? Teca reforça que a qualidade da serapilheira é o principal vetor de diferenciação entre os sistemas. Serapilheiras com alta relação C:N e grande teor de lignina, como as de Tectona grandis, tendem a formar compostos resistentes que privilegiam o enriquecimento húmico em detrimento das frações lábeis, reduzindo a velocidade de reciclagem e a disponibilidade imediata <span class="citation" data-cites="araujofilho2024">(<a href="../references.html#ref-araujofilho2024" role="doc-biblioref">Araújo Filho et al., 2024</a>)</span>. Em contraposição, resíduos com maior labilidade (por exemplo, consórcios leguminosos) alimentam o pool lábil e mantêm a renovação rápida dos nutrientes, condição que pode ser obtida pela introdução de adubação verde e pela diversificação de espécies arbóreas nos talhões.</p>
<p>Para o intervalo de variação de ß(húmico) de 1.180 (Agricultura) a 1.372 (Teca) representa amplitude relativa de 16.2%, magnitude expressiva considerando que o modelo já explica 95.9% da variância em cenários ótimos. Tal amplitude traduz-se em recomendações práticas: (i) manter ß próximo a 1.27 nos sistemas conservacionistas (Cerrado, Mogno) por meio da proteção do horizonte superficial; (ii) sustentar programas de adubação e cobertura morta na Agricultura para evitar colapso do pool húmico; e (iii) adotar estratégias de descompactação e enriquecimento com espécies de baixa relação C:N nas plantações de Teca, uma vez que o coeficiente elevado não compensa as restrições físicas que limitam a disponibilização dos nutrientes.</p>
<table class="caption-top table">
<caption>Tabela 5 - Coeficientes de caminho estratificados por uso da terra. Valores padronizados indicam a magnitude das relações estruturais em cada ambiente. Valores positivos indicam efeitos diretos; negativos, efeitos inversos ou ajustes de colinearidade.</caption>
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Uso da Terra</th>
<th>N_húmico ? N_total</th>
<th>N_lábil ? N_total</th>
<th>P_húmico ? P_total</th>
<th>P_lábil ? P_total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cerrado</td>
<td>1.286</td>
<td>-0.313</td>
<td>1.286</td>
<td>-0.313</td>
</tr>
<tr class="even">
<td>Agricultura</td>
<td>1.180</td>
<td>-0.237</td>
<td>1.180</td>
<td>-0.237</td>
</tr>
<tr class="odd">
<td>Mogno-africano</td>
<td>1.271</td>
<td>-0.277</td>
<td>1.271</td>
<td>-0.277</td>
</tr>
<tr class="even">
<td>Eucalipto</td>
<td>1.275</td>
<td>-0.283</td>
<td>1.275</td>
<td>-0.283</td>
</tr>
<tr class="odd">
<td>Teca</td>
<td>1.372</td>
<td>-0.445</td>
<td>1.372</td>
<td>-0.445</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="integração-fuzzy-da-funcionalidade-edáfica-índice-de-sustentabilidade-fsnsi" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="integração-fuzzy-da-funcionalidade-edáfica-índice-de-sustentabilidade-fsnsi">Integração fuzzy da funcionalidade edáfica: Índice de Sustentabilidade (FSNSI)</h2>
<section id="sistema-de-inferência-fuzzy-e-funções-de-pertinência" class="level3" data-number="4.0.5">
<h3 data-number="4.0.5" class="anchored" data-anchor-id="sistema-de-inferência-fuzzy-e-funções-de-pertinência"><span class="header-section-number">4.0.5</span> 3.3.1 Sistema de inferência fuzzy e funções de pertinência</h3>
<p>O Índice Fuzzy de Sustentabilidade Edáfica (FSNSI) foi construído a partir de um sistema de inferência fuzzy do tipo Mamdani, integrando três variáveis de entrada (N total, P total e densidade do solo) e uma variável de saída (FSNSI, escala 0-10). As variáveis de entrada foram normalizadas para escala 0-10, com densidade do solo recebendo inversão matemática para refletir sua relação negativa com a funcionalidade edáfica. O sistema fuzzy utilizou funções de pertinência triangulares para representar três classes linguísticas (baixa, média e alta) em cada variável de entrada, e três classes na saída (baixa: 0-3.33, média: 3.34-6.66, alta: 6.67-10.0).</p>
<p>A Figura 7 ilustra as funções de pertinência para as variáveis de entrada, evidenciando a estrutura lógica do sistema fuzzy. As regiões de sobreposição entre classes permitem transições graduais entre estados linguísticos, característica fundamental da lógica fuzzy que distingue essa abordagem de classificações discretas convencionais. Para N total e P total, valores normalizados abaixo de 3.3 foram classificados como “baixos”, entre 3.3 e 6.7 como “médios”, e acima de 6.7 como “altos”. A densidade do solo foi categorizada como “baixa” (&lt; 1.2 g/cm³), “média” (1.2-1.4 g/cm³) e “alta” (&gt; 1.4 g/cm³).</p>
<div id="fig:7" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="../figures/funcoes_pertinencia_entrada.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Figura 7. Funções de pertinência fuzzy para as variáveis de entrada (N total, P total e densidade do solo) do sistema de inferência Mamdani utilizado no cálculo do FSNSI. As regiões de sobreposição permitem transições graduais entre classes linguísticas (baixa, média, alta).</figcaption>
</figure>
</div>
<p>A Figura 8 apresenta a função de pertinência da variável de saída (FSNSI), estruturada em três categorias de funcionalidade edáfica: baixa (0-3.33, indicando degradação severa), média (3.34-6.66, funcionalidade moderada) e alta (6.67-10.0, sustentabilidade plena). O sistema foi configurado com 16 regras de inferência (2³ = 8 regras base, duplicadas para considerar assimetrias nas combinações de entrada), seguindo a estrutura lógica: “SE N total é X E P total é Y E densidade é Z, ENTÃO FSNSI é W”. As regras foram definidas com base em conhecimento pedológico especializado, priorizando combinações sinérgicas entre alta disponibilidade química de nutrientes e baixa compactação. O método de defuzzificação adotado foi o centroide, que calcula o valor crisp de saída como o centro de gravidade da função de pertinência resultante da agregação das regras ativadas.</p>
<div id="fig:8" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="../figures/funcao_pertinencia_saida.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Figura 8. Função de pertinência fuzzy para a variável de saída FSNSI (Fuzzy Soil Nutrient Sustainability Index). Três classes linguísticas representam níveis de funcionalidade edáfica: baixa (0-3.33), média (3.34-6.66) e alta (6.67-10.0).</figcaption>
</figure>
</div>
<p>Ainda, a análise do FSNSI revelou diferenciação significativa entre os sistemas de uso da terra avaliados (Figura 9, Tabela 6). O Eucalipto apresentou o maior FSNSI médio (6.07 ± 2.78, n = 40), classificado predominantemente como funcionalidade “alta” (60% das amostras), seguido por Mogno-africano (4.54 ± 2.89), Cerrado nativo (4.42 ± 2.89), Agricultura convencional (4.25 ± 2.57) e Teca (2.77 ± 1.16), este último com funcionalidade predominantemente “baixa” (62.5% das amostras). A análise de variância (ANOVA) confirmou diferenças significativas entre os usos (F = 12.84, p &lt; 0.001), com o teste de Tukey HSD identificando três agrupamentos estatísticos distintos.</p>
<div id="fig:9" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="../figures/boxplot_fsnsi_uso_terra.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Figura 9. Distribuição do Índice Fuzzy de Sustentabilidade Edáfica (FSNSI) por uso da terra. Boxplots com padrões visuais distintos para cada sistema. Letras diferentes indicam diferenças significativas pelo teste de Tukey HSD (p &lt; 0.05). Pontos representam valores individuais.</figcaption>
</figure>
</div>
<p>O desempenho do Eucalipto (FSNSI = 6.07) diferencia-se significativamente do Cerrado nativo (FSNSI = 4.42), com diferença estatisticamente significativa (? = 1.64, IC 95%: 0.07-3.22, p = 0.036). Esse resultado contraria a expectativa inicial de que a vegetação nativa representaria o estado de funcionalidade máxima. A explicação reside na combinação entre: elevado aporte de serapilheira rica em lignina e compostos fenólicos pelo Eucalipto, favorecendo a formação de frações húmicas estáveis de N e P; sistema radicular profundo que promove bioperturbação do solo, reduzindo localmente a densidade aparente nas camadas superficiais; e ausência de remoção de biomassa por colheita no sistema avaliado (povoamento não manejado há 11 anos), permitindo acúmulo contínuo de matéria orgânica. <span class="citation" data-cites="silva2024">Silva et al. (<a href="../references.html#ref-silva2024" role="doc-biblioref">2024</a>)</span> documentaram que a conversão de áreas nativas de Cerrado para sistemas agrícolas altera profundamente a dinâmica de emissão de CO2 e os estoques de carbono no solo, enquanto <span class="citation" data-cites="leal2024">Leal et al. (<a href="../references.html#ref-leal2024" role="doc-biblioref">2024</a>)</span> demonstraram que plantios de Acacia e Eucalyptus modificam a composição molecular das frações de matéria orgânica particulada (POM) e associada aos minerais (MAOM) em solos de pastagens nativas subtropicais, sugerindo que a qualidade dos resíduos vegetais exerce papel determinante na estabilização de nutrientes. O Cerrado nativo apresentou FSNSI médio de 4.42, classificado como funcionalidade “média”, com distribuição bimodal: 50% das amostras na classe “baixa” e 40% na classe “alta” (Tabela 6). Essa heterogeneidade reflete a estratificação vertical natural dos solos de Cerrado, onde as camadas superficiais (0-20 cm) concentram a maior parte da matéria orgânica e apresentam densidade reduzida (média de 0.97 g cm?³), enquanto as camadas subsuperficiais (30-50 cm) apresentam empobrecimento químico e adensamento natural. A amplitude de valores do FSNSI no Cerrado (1.56 a 8.57, range = 7.01) foi a maior entre todos os sistemas.istemas, evidenciando gradientes verticais acentuados.</p>
<p><strong>Tabela 6.</strong> Estatísticas descritivas do Índice Fuzzy de Sustentabilidade Edáfica (FSNSI) por uso da terra, incluindo medidas de tendência central, dispersão e distribuição das classes linguísticas de funcionalidade.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 2%">
<col style="width: 10%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 7%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 16%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Uso da Terra</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">FSNSI Médio</th>
<th style="text-align: right;">DP</th>
<th style="text-align: right;">EP</th>
<th style="text-align: right;">CV (%)</th>
<th style="text-align: right;">Mín.</th>
<th style="text-align: right;">Q1</th>
<th style="text-align: right;">Mediana</th>
<th style="text-align: right;">Q3</th>
<th style="text-align: right;">Máx.</th>
<th style="text-align: left;">Classe Predominante</th>
<th style="text-align: left;">Distribuição de Classes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Eucalipto</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">6.07</td>
<td style="text-align: right;">2.78</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: right;">45.8</td>
<td style="text-align: right;">1.63</td>
<td style="text-align: right;">3.98</td>
<td style="text-align: right;">7.46</td>
<td style="text-align: right;">8.35</td>
<td style="text-align: right;">8.57</td>
<td style="text-align: left;">Alta</td>
<td style="text-align: left;">Alta (60%); Baixa (25%); Média (15%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mogno-africano</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">4.54</td>
<td style="text-align: right;">2.89</td>
<td style="text-align: right;">0.46</td>
<td style="text-align: right;">63.6</td>
<td style="text-align: right;">1.50</td>
<td style="text-align: right;">1.61</td>
<td style="text-align: right;">4.18</td>
<td style="text-align: right;">8.30</td>
<td style="text-align: right;">8.66</td>
<td style="text-align: left;">Baixa</td>
<td style="text-align: left;">Baixa (40%); Média (30%); Alta (30%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cerrado</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">4.42</td>
<td style="text-align: right;">2.89</td>
<td style="text-align: right;">0.46</td>
<td style="text-align: right;">65.3</td>
<td style="text-align: right;">1.56</td>
<td style="text-align: right;">1.62</td>
<td style="text-align: right;">4.16</td>
<td style="text-align: right;">6.88</td>
<td style="text-align: right;">8.57</td>
<td style="text-align: left;">Baixa</td>
<td style="text-align: left;">Baixa (50%); Alta (40%); Média (10%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Agricultura</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">4.25</td>
<td style="text-align: right;">2.57</td>
<td style="text-align: right;">0.41</td>
<td style="text-align: right;">60.6</td>
<td style="text-align: right;">1.31</td>
<td style="text-align: right;">1.66</td>
<td style="text-align: right;">4.18</td>
<td style="text-align: right;">5.21</td>
<td style="text-align: right;">8.21</td>
<td style="text-align: left;">Baixa</td>
<td style="text-align: left;">Baixa (37.5%); Média (37.5%); Alta (22.5%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Teca</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">2.77</td>
<td style="text-align: right;">1.16</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">41.8</td>
<td style="text-align: right;">1.42</td>
<td style="text-align: right;">1.71</td>
<td style="text-align: right;">2.82</td>
<td style="text-align: right;">3.80</td>
<td style="text-align: right;">4.55</td>
<td style="text-align: left;">Baixa</td>
<td style="text-align: left;">Baixa (62.5%); Média (32.5%)</td>
</tr>
</tbody>
</table>
<p>DP: desvio-padrão; EP: erro-padrão; CV: coeficiente de variação; Q1: primeiro quartil; Q3: terceiro quartil.</p>
<p>A Agricultura convencional registrou FSNSI médio de 4.25, com distribuição equilibrada entre classes “baixa” e “média” (37.5% cada), indicando funcionalidade comprometida, mas não colapsada. O coeficiente de variação moderado (60.6%) sugere certa homogeneização vertical do perfil edáfico decorrente do preparo mecanizado recorrente (aração e gradagem), que promove mistura das camadas e reduz os gradientes naturais. No entanto, 22.5% das amostras ainda atingiram classificação “alta”, possivelmente associadas às camadas superficiais recém-adubadas ou a microsítios com acúmulo residual de matéria orgânica.</p>
<p>O Mogno-africano apresentou desempenho intermediário (FSNSI = 4.54), com distribuição relativamente equilibrada entre as três classes (40% baixa, 30% média, 30% alta). Esse padrão sugere transição entre estado de degradação e recuperação funcional, reflexo do manejo menos intensivo comparativamente à agricultura. O sistema não diferiu estatisticamente do Cerrado (p = 0.999) nem da Agricultura (p = 0.986), posicionando-se como sistema de “transição ecológica”, com potencial de melhoria da funcionalidade mediante ajustes no manejo (e.g., manutenção de cobertura morta, redução de intervenções mecanizadas).</p>
</section>
<section id="estratificação-vertical-do-fsnsi" class="level3" data-number="4.0.6">
<h3 data-number="4.0.6" class="anchored" data-anchor-id="estratificação-vertical-do-fsnsi"><span class="header-section-number">4.0.6</span> 3.3.3 Estratificação vertical do FSNSI</h3>
<p>A análise estratificada por profundidade revelou gradientes verticais acentuados no FSNSI, com padrões distintos entre os usos da terra (Figura 10). De modo geral, observou-se decréscimo significativo da funcionalidade edáfica com o aumento da profundidade, reflexo da redução conjunta dos estoques de N e P e do aumento da densidade do solo nas camadas subsuperficiais. As camadas 0-10 cm e 10-20 cm apresentaram sistematicamente os maiores valores de FSNSI, concentrando 78% das amostras classificadas como funcionalidade “alta”. No Cerrado nativo, a dicotomia superfície-subsuperfície foi acentuada: FSNSI médio de 7.04 ± 0.05 em 0-10 cm (funcionalidade “alta”) versus 1.59 ± 0.03 em 40-50 cm (funcionalidade “baixa”). Esse gradiente vertical de 445% reflete a arquitetura biogeoquímica natural dos Latossolos sob Cerrado, onde o sistema radicular superficial promove ciclagem intensa de nutrientes nas camadas superiores, enquanto as camadas profundas apresentam elevada intemperização, lixiviação histórica de nutrientes e adensamento coesivo natural.</p>
<div id="fig:10" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="../figures/fsnsi_profundidade_uso_terra.png" class="img-fluid figure-img" style="width:95.0%"></p>
<figcaption>Figura 10. Distribuição do FSNSI estratificado por profundidade e uso da terra. Padrões visuais distintos identificam cada sistema. Observa-se decréscimo sistemático da funcionalidade edáfica com o aumento da profundidade em todos os sistemas avaliados.</figcaption>
</figure>
</div>
<p>O Eucalipto manteve FSNSI elevado até 20 cm de profundidade (média de 8.15 em 0-10 cm e 8.18 em 10-20 cm), mas apresentou declínio abrupto a partir de 20 cm (3.97 em 20-30 cm), sugerindo concentração superficial dos benefícios do aporte de serapilheira. A Agricultura exibiu padrão similar, com valores altos nas camadas superficiais devido à adubação (8.05 em 0-10 cm), mas colapso funcional a partir de 30 cm (1.68 em 30-40 cm), evidenciando que os benefícios do manejo químico não alcançam as camadas subsuperficiais.</p>
<p>A Teca apresentou o padrão mais homogêneo verticalmente, com pouca variação entre profundidades (range = 1.79 a 3.35), sugerindo que a degradação funcional é generalizada ao longo de todo o perfil. Esse resultado reforça a necessidade de intervenções de manejo específicas para essa espécie, incluindo adubação de manutenção, incorporação de matéria orgânica e práticas de descompactação mecânica ou biológica.</p>
</section>
<section id="correlações-entre-variáveis-de-entrada-e-fsnsi" class="level3" data-number="4.0.7">
<h3 data-number="4.0.7" class="anchored" data-anchor-id="correlações-entre-variáveis-de-entrada-e-fsnsi"><span class="header-section-number">4.0.7</span> 3.3.4 Correlações entre variáveis de entrada e FSNSI</h3>
<p>A análise de correlação de Pearson (Tabela 7) confirmou que N total e P total foram os preditores mais fortemente associados ao FSNSI (r = 0.789, p &lt; 0.001 para ambos), explicando aproximadamente 62% da variância do índice (r² = 0.622). Esse resultado valida a estrutura lógica do sistema fuzzy, demonstrando que a disponibilidade química de nutrientes constitui o fator primário na determinação da funcionalidade edáfica. As frações lábeis e húmicas de N e P também apresentaram correlações positivas significativas (r = 0.616-0.627, p &lt; 0.001), reforçando a interdependência funcional entre compartimentos químicos.</p>
<p><strong>Tabela 7.</strong> Coeficientes de correlação de Pearson entre variáveis edáficas e o Índice Fuzzy de Sustentabilidade Edáfica (FSNSI), incluindo intervalos de confiança 95% e níveis de significância estatística.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 20%">
<col style="width: 35%">
<col style="width: 11%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variável</th>
<th style="text-align: right;">Correlação (r)</th>
<th style="text-align: center;">Intervalo de Confiança 95%</th>
<th style="text-align: left;">p-valor</th>
<th style="text-align: left;">Significância</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">N total</td>
<td style="text-align: right;">+0.789</td>
<td style="text-align: center;">0.730 a 0.837</td>
<td style="text-align: left;">&lt; 2e-16</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="even">
<td style="text-align: left;">P total</td>
<td style="text-align: right;">+0.789</td>
<td style="text-align: center;">0.730 a 0.837</td>
<td style="text-align: left;">&lt; 2e-16</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">N lábil</td>
<td style="text-align: right;">+0.627</td>
<td style="text-align: center;">0.533 a 0.705</td>
<td style="text-align: left;">&lt; 2e-16</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="even">
<td style="text-align: left;">P lábil</td>
<td style="text-align: right;">+0.627</td>
<td style="text-align: center;">0.533 a 0.705</td>
<td style="text-align: left;">&lt; 2e-16</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">N húmico</td>
<td style="text-align: right;">+0.616</td>
<td style="text-align: center;">0.521 a 0.696</td>
<td style="text-align: left;">&lt; 2e-16</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="even">
<td style="text-align: left;">P húmico</td>
<td style="text-align: right;">+0.616</td>
<td style="text-align: center;">0.533 a 0.705</td>
<td style="text-align: left;">&lt; 2e-16</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Densidade do solo</td>
<td style="text-align: right;">-0.424</td>
<td style="text-align: center;">-0.545 a -0.318</td>
<td style="text-align: left;">1.15e-10</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="even">
<td style="text-align: left;">Areia</td>
<td style="text-align: right;">-0.439</td>
<td style="text-align: center;">-0.545 a -0.318</td>
<td style="text-align: left;">&lt; 2e-16</td>
<td style="text-align: left;">***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Argila</td>
<td style="text-align: right;">+0.267</td>
<td style="text-align: center;">0.094 a 0.359</td>
<td style="text-align: left;">0.001</td>
<td style="text-align: left;">**</td>
</tr>
<tr class="even">
<td style="text-align: left;">Silte</td>
<td style="text-align: right;">+0.230</td>
<td style="text-align: center;">0.132 a 0.392</td>
<td style="text-align: left;">&lt; 0.001</td>
<td style="text-align: left;">***</td>
</tr>
</tbody>
</table>
<p>*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05.</p>
<p>A densidade do solo apresentou correlação negativa moderada com o FSNSI (r = -0.424, p &lt; 0.001), confirmando seu papel como fator limitante transversal. Esse resultado é particularmente relevante, pois demonstra que a degradação física pode comprometer a funcionalidade edáfica mesmo em condições químicas favoráveis. Os mecanismos pelos quais a compactação afeta a funcionalidade edáfica incluem: (i) redução da porosidade total e, particularmente, dos macroporos (&gt; 50 µm), limitando a difusão de O2 para horizontes subsuperficiais e criando condições de hipoxia que favorecem processos anaeróbicos de desnitrificação (N2O, N2) e redução de formas oxidadas de P ligadas a Fe³?, com consequente volatilização de N e solubilização excessiva de P que pode ser perdido por lixiviação; (ii) restrição ao crescimento radicular, especialmente para espécies com sistemas de raízes pivotantes, limitando a exploração de camadas subsuperficiais ricas em nutrientes lixiviados e reduzindo a bioperturbação que naturalmente descompacta o solo; (iii) diminuição da atividade microbiana aeróbica devido à limitação de O2, comprometendo processos-chave como a mineralização de N orgânico, a solubilização de P por ácidos orgânicos exsudados por microrganianos e a humificação progressiva de resíduos vegetais; e (iv) redução da infiltração de água e aumento do escoamento superficial, favorecendo erosão laminar que remove seletivamente as frações finas do solo (argila, silte) ricas em MOS e nutrientes associados.</p>
<p>Estudos sobre mudança de uso da terra e frações húmicas corroboram esses padrões, demonstrando que a conversão de ecossistemas nativos altera profundamente o particionamento de N entre compartimentos funcionais. <span class="citation" data-cites="santos2024">Santos et al. (<a href="../references.html#ref-santos2024" role="doc-biblioref">2024</a>)</span> evidenciaram em Latossolo Vermelho sob diferentes coberturas no Tocantins que a Teca apresentou os maiores estoques de N total (11.47 Mg ha?¹), enquanto o Cerrado nativo exibiu os menores (10.16 Mg ha?¹), padrão consistente com os resultados do presente estudo. Sistemas florestais plantados concentraram formas mais estáveis (ácidos húmicos e humina), associadas ao maior input de serapilheira lignificada, enquanto a agricultura favoreceu acúmulo de formas lábeis (ácidos fúlvicos). A análise de redundância (RDA) explicou 47% da variação total, evidenciando gradientes de enriquecimento e estabilização de N que se alinham com os coeficientes estruturais ß elevados observados no PLS-SEM. Esses achados reforçam que práticas conservacionistas baseadas em plantios arbóreos com raízes profundas e input orgânico contínuo são essenciais para preservar a estabilidade de N e a sustentabilidade de Latossolos tropicais, especialmente em contextos de intensificação agrícola where soil physical degradation compromises chemical functionality.</p>
<p>Estudos prévios corroboram esses mecanismos: em Latossolos com densidade &gt; 1.5 g cm?³, a taxa de mineralização de N orgânico reduz-se em 35-48% comparativamente a solos bem estruturados (densidade &lt; 1.2 g cm?³), enquanto a emissão de N2O aumenta em 2-3 vezes devido à predominância de microsítios anaeróbicos. A compactação também altera a distribuição espacial das frações de P: em solos compactados, observa-se acúmulo relativo de P lábil nas camadas superficiais (0-10 cm) devido à redução da infiltração, enquanto as frações húmicas de P concentram-se em profundidade, criando gradientes verticais acentuados que comprometem a eficiência de uso do nutriente pelas plantas. Essa estratificação vertical excessiva é capturada pelo FSNSI através da penalização imposta pela densidade, que opera multiplicativamente sobre os índices de disponibilidade química: solos com densidade de 1.6 g cm?³ (observada em Teca e Pastagem) recebem penalização de aproximadamente 40% no FSNSI, mesmo apresentando teores adequados de N e P totais.</p>
<p>A textura do solo também influenciou o FSNSI, com areia correlacionando-se negativamente (r = -0.439, p &lt; 0.001) e argila positivamente (r = 0.267, p = 0.001), reflexo da maior capacidade de retenção de nutrientes e água em solos argilosos. Esse padrão é consistente com a teoria de proteção físico-química da MOS, segundo a qual frações finas do solo (argila &lt; 2 µm, silte 2-50 µm) formam complexos organo-minerais estáveis que protegem N e P contra mineralização rápida. Em solos arenosos, a baixa superfície específica (&lt; 5 m² g?¹) e a ausência de minerais reativos (predominância de quartzo inerte) limitam a adsorção de substâncias húmicas e a formação de microagregados, resultando em MOS menos estável e maior suscetibilidade à mineralização. A correlação positiva entre argila e FSNSI (r = 0.267) demonstra que, mesmo em Latossolos altamente intemperizados onde a mineralogia é dominada por caulinita de baixa atividade, o incremento no teor de argila ainda confere benefícios funcionais mensuráveis, provavelmente mediados pela maior retenção de água e pelo aumento da superfície disponível para adsorção de nutrientes e colonização microbiana.</p>
<p>Esses resultados reforçam a adequação da abordagem fuzzy para integração de múltiplas dimensões da funcionalidade edáfica, capturando simultaneamente aspectos químicos (disponibilidade de nutrientes), físicos (compactação) e mineralógicos (textura). A lógica fuzzy permitiu traduzir essas relações quantitativas em um índice interpretável, facilitando a identificação de sistemas prioritários para intervenções de manejo conservacionista e recuperação da qualidade do solo. A validação dessas relações por meio de análise de correlação multivariada demonstra que o FSNSI não constitui mera síntese empírica, mas reflete processos biogeoquímicos fundamentais que governam a funcionalidade edáfica em ambientes tropicais. A magnitude das correlações (r = 0.62-0.79 para variáveis químicas, r = -0.42 para densidade) situa-se na faixa esperada para sistemas pedológicos complexos onde múltiplos fatores interagem de forma não linear, validando a robustez do sistema fuzzy como ferramenta diagnóstica integrativa.</p>
<p>A combinação de PLSR, PLS-SEM e inferência fuzzy sintetizou a dinâmica de N e P em múltiplas escalas, alinhando-se às recomendações metodológicas para sistemas complexos <span class="citation" data-cites="hair2021">(<a href="../references.html#ref-hair2021" role="doc-biblioref">Hair et al., 2021</a>)</span>. A etapa PLSR destacou as frações húmicas como principais preditoras dos estoques totais, enquanto o PLS-SEM quantificou a dominância dos compartimentos NTAH, NTHum, PTAH e PTHum (ß = 1.286 para N_húmico ? N_total), em consonância com evidências de que substâncias húmicas constituem os principais reservatórios estáveis em Latossolos manejados <span class="citation" data-cites="pegoraro2011 ferreira2021">(<a href="../references.html#ref-pegoraro2011" role="doc-biblioref">Pegoraro et al., 2011</a>, <a href="../references.html#ref-ferreira2021" role="doc-biblioref">Ferreira et al., 2021</a>)</span>. Em contraste, coeficientes negativos atribuídos às frações lábeis refletem a transferência contínua desses pools para formas mais recalcitrantes, dinâmica também reportada em cronossequências tropicais <span class="citation" data-cites="marinhojunior2021">(<a href="../references.html#ref-marinhojunior2021" role="doc-biblioref">Marinho Junior et al., 2021</a>)</span>.</p>
<p>O FSNSI expôs diferenças funcionais claras entre os usos da terra em que, o Eucalipto apresentou índice superior ao Cerrado (6.07 versus 4.42), compatível com a capacidade dessa espécie de enriquecer frações húmicas e melhorar a estrutura física quando resíduos não são removidos <span class="citation" data-cites="crespo2024">(<a href="../references.html#ref-crespo2024" role="doc-biblioref">Crespo et al., 2024</a>)</span>. A Teca exibiu o menor desempenho (2.77), reforçando que serapilheiras altamente recalcitrantes e compactação residual limitam a reciclagem de nutrientes e elevam a penalização física do índice <span class="citation" data-cites="santos2024">(<a href="../references.html#ref-santos2024" role="doc-biblioref">Santos et al., 2024</a>)</span>. Sistemas agrícolas mantiveram valores intermediários (4.25), indicando que a adubação mineral sustenta a disponibilidade superficial, mas não reverte a degradação das camadas subsuperficiais.</p>
<p>As correlações confirmaram que N total e P total explicam parte substancial da variação do FSNSI (r = 0.789), porém a densidade do solo relacionou-se negativamente com o índice (r = -0.424), ressaltando que a degradação física continua sendo limitante transversal mesmo em solos quimicamente enriquecidos <span class="citation" data-cites="santos2024">(<a href="../references.html#ref-santos2024" role="doc-biblioref">Santos et al., 2024</a>)</span>. Assim, a interpretação integrada das três abordagens evidencia que indicadores isolados podem mascarar desequilíbrios, enquanto o FSNSI agrega dimensões químicas e físicas coerentes com a arquitetura estrutural revelada pelo PLS-SEM, oferecendo ferramenta robusta para priorização de ações de manejo e restauração.</p>
</section>
</section>
<section id="articulação-entre-plsr-pls-sem-e-inferência-fuzzy" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="articulação-entre-plsr-pls-sem-e-inferência-fuzzy">Articulação entre PLSR, PLS-SEM e inferência fuzzy</h2>
<p>A integração das três abordagens analíticas (PLSR, PLS-SEM e inferência fuzzy) permitiu compreensão multiescalar e multidimensional da dinâmica de N e P nos solos estudados. A análise PLSR identificou as frações mais relevantes para predição dos estoques totais, fornecendo subsídios para seleção de indicadores de monitoramento. O modelo PLS-SEM explicitou as relações causais entre compartimentos funcionais, quantificando as contribuições relativas das formas lábeis e húmicas. Por fim, o sistema fuzzy traduziu essas informações em índice sintético de funcionalidade, incorporando a dimensão física (densidade do solo) como fator limitante.</p>
<p>A estrutura do modelo PLS-SEM demonstra que as frações húmicas (NTAH, NTHum, PTAH, PTHum) funcionam como reservatórios preferenciais para N e P, com contribuições dominantes na predição dos pools totais. Os coeficientes de caminho (ß = 1.286 para N_húmico ? N_total, ß = -0.313 para N_lábil ? N_total no ambiente Cerrado) evidenciam interações entre compartimentos, onde o enriquecimento da fração húmica amplifica o efeito no estoque total, enquanto a fração lábil apresenta relação negativa, refletindo dinâmica de particionamento fisiológico entre pools. A magnitude variável desses coeficientes entre os cinco ambientes (Cerrado, Agricultura, Mogno, Eucalipto, Teca) reforça a hipótese de que o manejo e a cobertura vegetal modulam as trajetórias de ciclagem de nutrientes.</p>
<p>A análise fuzzy revelou padrão contrastante: o Eucalipto apresentou funcionalidade edáfica superior ao Cerrado nativo (FSNSI de 6.07 versus 4.42, p = 0.036), resultado que pode ser explicado pela natureza não manejada do povoamento de Eucalipto avaliado (11 anos sem colheita), que permitiu acúmulo contínuo de serapilheira rica em compostos recalcitrantes, promovendo humificação intensa e enriquecimento das frações húmicas de N e P. Adicionalmente, o sistema radicular do Eucalipto promove bioperturbação que reduz localmente a densidade aparente, atenuando a penalização física no cálculo do FSNSI.</p>
<p>Essa interpretação articula-se com os resultados das análises PLSR e PLS-SEM: se as frações húmicas são preditoras-chave dos estoques totais (VIP &gt; 1.0) e o Eucalipto favorece seu acúmulo, então é coerente que esse sistema expresse funcionalidade edáfica elevada. A aparente contradição com a expectativa de superioridade do Cerrado reside no fato de que o FSNSI captura funcionalidade bioquímica corrente, não necessariamente equilíbrio ecológico de longo prazo ou biodiversidade edáfica. Sistemas florestais plantados podem, sob condições específicas (ausência de colheita, baixa intensidade de manejo), promover acúmulo transitório de nutrientes superior ao de ecossistemas naturais oligotróficos como o Cerrado.</p>
<p>O desempenho da Teca (FSNSI = 2.77, 54% inferior ao Eucalipto, p &lt; 0.001) evidencia o papel determinante da qualidade da serapilheira e do manejo pós-implantação. A Teca, espécie decídua com folhas de relação C:N elevada e baixa taxa de decomposição, promove aporte de resíduos de qualidade inferior para humificação. Adicionalmente, a compactação residual do preparo mecanizado (densidade média de 1.62 g cm?³) não foi mitigada ao longo do tempo, resultando em penalização física persistente no FSNSI. Esse resultado indica necessidade de práticas complementares em sistemas de Teca, incluindo consórcios com leguminosas fixadoras de N, adubação orgânica e descompactação biológica.</p>
<p>A Agricultura convencional posicionou-se em estado intermediário (FSNSI = 4.25), não diferindo estatisticamente do Cerrado (p = 0.998) nem do Mogno (p = 0.986). Esse resultado sugere que, sob manejo químico adequado (adubação NPK), é possível manter funcionalidade edáfica comparável à vegetação nativa, ao menos em termos de disponibilidade química de nutrientes. No entanto, a distribuição bimodal das classes (37.5% “baixa” e 37.5% “média”) revela heterogeneidade vertical pronunciada, com funcionalidade concentrada nas camadas superficiais adubadas e colapso nas camadas subsuperficiais, padrão não observado no Cerrado. Esse contraste reforça que a adubação mineral compensa parcialmente a degradação química, mas não restaura os gradientes verticais naturais nem a estrutura física do solo.</p>
<p>A análise de correlação confirmou que N total e P total explicam 62% da variância do FSNSI (r = 0.789, r² = 0.622), validando a estrutura lógica do sistema fuzzy. No entanto, a correlação negativa da densidade do solo (r = -0.424, p &lt; 0.001) demonstra que a degradação física atua como fator limitante transversal, reduzindo o FSNSI mesmo em solos quimicamente enriquecidos. Esse resultado tem implicação prática: estratégias de manejo devem considerar simultaneamente fertilidade química e qualidade física, pois o comprometimento de qualquer dimensão restringe a funcionalidade global do sistema.</p>
<p>Essa síntese integrativa reforça a necessidade de abordagens multiescalares para avaliação da sustentabilidade edáfica em ambientes tropicais. Indicadores isolados podem mascarar desequilíbrios funcionais que somente emergem quando se considera simultaneamente a compartimentalização química, as relações estruturais entre pools de nutrientes quantificadas por modelagem PLS-SEM, e a integração com atributos físicos restritivos (densidade do solo como penalizador). O FSNSI, por incorporar essas múltiplas dimensões em índice interpretável e por ter sua fundamentação validada pela correspondência com os caminhos de análise PLS-SEM, constitui ferramenta adequada para monitoramento da funcionalidade edáfica e identificação de sistemas prioritários para restauração ecológica.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-araujofilho2024" class="csl-entry" role="listitem">
Araújo Filho, R. N. de, M. B. G. dos S. Freire, F. J. Freire, R. L. C. Ferreira, L. M. Pereira &amp; L. D. V. Santos (2024). Litter dynamics and nutrient stocks in a chronosequence of hyperxerophilous forest under the effect of clear felling. <em>Forest Ecology and Management</em>, <strong>567</strong> p. 122087. <a href="https://doi.org/10.1016/j.foreco.2024.122087">https://doi.org/10.1016/j.foreco.2024.122087</a>
</div>
<div id="ref-crespo2024" class="csl-entry" role="listitem">
Crespo, C. M. G., V. C. Piscoya, R. C. P. de Melo, L. M. Pereira, L. D. V. Santos, F. S. R. Holanda, et al. (2024). Topographic modulation of soil functional indicators in shaded coffee agroforestry systems: A multivariate and network-based approach. <em>Agronomy</em>, <strong>14</strong> p. 2847. <a href="https://doi.org/10.3390/agronomy14122847">https://doi.org/10.3390/agronomy14122847</a>
</div>
<div id="ref-ferreira2021" class="csl-entry" role="listitem">
Ferreira, G. W. D., F. C. C. Oliveira, E. M. B. Soares, J. Schnecker, I. R. Silva &amp; A. S. Grandy (2021). Retaining eucalyptus harvest residues promotes different pathways for particulate and mineral‐associated organic matter. <em>Ecosphere</em>, <strong>12</strong>. <a href="https://doi.org/10.1002/ecs2.3439">https://doi.org/10.1002/ecs2.3439</a>
</div>
<div id="ref-hair2021" class="csl-entry" role="listitem">
Hair, J. F., G. T. M. Hult, C. M. Ringle &amp; M. Sarstedt (2021). <em>A primer on partial least squares structural equation modeling (PLS-SEM)</em>. Sage Publications: 3rd ed.
</div>
<div id="ref-helfenstein2020" class="csl-entry" role="listitem">
Helfenstein, J., J. Jegminat, T. I. McLaren, E. Frossard &amp; A. Oberson (2020). Soil organic phosphorus transformations in response to management and environmental changes: A review. <em>Soil Biology and Biochemistry</em>, <strong>156</strong> p. 108193. <a href="https://doi.org/10.1016/j.soilbio.2021.108193">https://doi.org/10.1016/j.soilbio.2021.108193</a>
</div>
<div id="ref-leal2024" class="csl-entry" role="listitem">
Leal, O. dos A., G. S. Santana, H. Knicker, F. J. González-Vila, J. A. González-Pérez &amp; D. P. Dick (2024). Acacia and eucalyptus plantations modify the molecular composition of density organic matter fractions of subtropical native pasture soils. <em>Geoderma</em>, <strong>441</strong> p. 116745. <a href="https://doi.org/10.1016/j.geoderma.2023.116745">https://doi.org/10.1016/j.geoderma.2023.116745</a>
</div>
<div id="ref-marinhojunior2021" class="csl-entry" role="listitem">
Marinho Junior, J. L., V. C. Piscoya, M. M. Fernandes, S. B. Gonçalves, F. S. R. Holanda, M. Cunha Filho, et al. (2021). Carbon dynamics in humic fractions of soil organic matter under different vegetation cover in southern tocantins. <em>Floresta e Ambiente</em>, <strong>28</strong>. <a href="https://doi.org/10.1590/2179-8087-floram-2020-0024">https://doi.org/10.1590/2179-8087-floram-2020-0024</a>
</div>
<div id="ref-paul2016" class="csl-entry" role="listitem">
Paul, E. A. (2016). The nature and dynamics of soil organic matter: Reconsiderations within the current paradigm. <em>Soil Biology and Biochemistry</em>, <strong>98</strong> p. 109–123. <a href="https://doi.org/10.1016/j.soilbio.2016.04.001">https://doi.org/10.1016/j.soilbio.2016.04.001</a>
</div>
<div id="ref-pegoraro2011" class="csl-entry" role="listitem">
Pegoraro, R. F., I. R. da Silva, R. F. de Novais, N. F. de Barros, S. Fonseca &amp; C. S. Dambroz (2011). Estoques de carbono e nitrogênio nas frações da matéria orgânica em argissolo sob eucalipto e pastagem. <em>Ciência Florestal</em>, <strong>21</strong> p. 261–273. <a href="https://doi.org/10.5902/198050983230">https://doi.org/10.5902/198050983230</a>
</div>
<div id="ref-santos2024" class="csl-entry" role="listitem">
Santos, L. D. V., L. M. Pereira, S. A. B. da Silva, F. S. R. Holanda, R. C. P. de Melo, M. Cunha Filho, et al. (2024). Land use change and its effects on soil nitrogen stocks and humic fractions in latosol from brazilian cerrado. <em>Soil Science Society of America Journal</em>, <strong>88</strong> p. 1234–1248. <a href="https://doi.org/10.1002/saj2.20567">https://doi.org/10.1002/saj2.20567</a>
</div>
<div id="ref-sekaran2020" class="csl-entry" role="listitem">
Sekaran, U., J. R. Loya, G. O. Abagandura, S. Subramanian, V. Owens &amp; S. Kumar (2020). Intercropping of kura clover (trifolium ambiguum m. Bieb) with prairie cordgrass (spartina pectinata link.) enhanced soil biochemical activities and microbial community structure. <em>Applied Soil Ecology</em>, <strong>147</strong>. <a href="https://doi.org/10.1016/j.apsoil.2019.103427">https://doi.org/10.1016/j.apsoil.2019.103427</a>
</div>
<div id="ref-silva2024" class="csl-entry" role="listitem">
Silva, B. de O., M. R. Moitinho, A. R. Panosso, D. M. da S. Oliveira, R. Montanari, M. L. T. de Moraes, et al. (2024). Implications of converting native forest areas to agricultural systems on the dynamics of CO2 emission and carbon stock in a cerrado soil, brazil. <em>Journal of Environmental Management</em>, <strong>358</strong> p. 120796. <a href="https://doi.org/10.1016/j.jenvman.2024.120796">https://doi.org/10.1016/j.jenvman.2024.120796</a>
</div>
<div id="ref-tivet2013" class="csl-entry" role="listitem">
Tivet, F., J. C. M. Sá, R. Lal, C. Briedis, P. R. Borszowskei &amp; D. C. Hartman (2013). Aggregate c depletion by plowing and its restoration by no-till cropping systems under subtropical and tropical conditions. <em>Soil and Tillage Research</em>, <strong>126</strong> p. 203–218. <a href="https://doi.org/10.1016/j.still.2012.09.006">https://doi.org/10.1016/j.still.2012.09.006</a>
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/03-methodology.html" class="pagination-link" aria-label="Metodologia">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Metodologia</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/06-conclusion.html" class="pagination-link" aria-label="Conclusão">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Conclusão</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>